name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: install python deps
      run: python -m pip install -r requirements.txt --user
    - name: install laplack
      run: sudo apt-get install liblapacke-dev
    - name: install blas
      run: sudo apt-get install libblas-dev
    - name: install
      run: ./install.sh
    - name: check install
      run: python -c "import vnlb.pylib"

